added : imf support, needed for exr image files

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -46,6 +46,8 @@ ac_gdz_conf_package_jasper='0'
 ac_gdz_conf_package_jasper_e1='0'
 ac_gdz_conf_package_png='0'
 ac_gdz_conf_package_png_e1='0'
+ac_gdz_conf_package_imf='0'
+ac_gdz_conf_package_imf_e1='0'
 ac_gdz_conf_package_mng='0'
 ac_gdz_conf_package_mng_e1='0'
 ac_gdz_conf_package_gif='0'
@@ -714,6 +716,72 @@ else
 	ac_gdz_png_dir=
 	ac_gdz_png_incdir=
 	ac_gdz_png_libdir=
+fi
+
+
+dnl ############# imf Settings #####################
+
+AC_ARG_ENABLE(imf,     [  --enable-imf                        Build with imf support],
+			,enable_imf=no) 
+AC_ARG_WITH(imf,     [  --with-imf=DIR                      Use DIR/lib DIR/include to find the imf files],
+			,with_imf=) 
+AC_ARG_WITH(imfincludedir,     [  --with-imfincludedir=DIR            Use imf includes from the given directory],
+			,with_imfincludedir=) 
+AC_ARG_WITH(imflibdir,     [  --with-imflibdir=DIR                Use imf lib from the given directory],
+			,with_imflibdir=) 
+
+if test "$enable_imf" = no && test "$with_imf" = yes; then
+    enable_imf=yes
+    with_imf=
+fi
+
+if test "$enable_imf" = no && test "$with_imf"X != "X"; then
+    enable_imf=yes
+fi
+
+if test "$enable_imf" = yes; then
+	ac_gdz_imf_incdir=
+	ac_gdz_imf_libdir=
+	ac_gdz_conf_package_defs=$ac_gdz_conf_package_defs' -DOSG_WITH_IMF'
+	ac_gdz_conf_package_imf='1'
+	ac_gdz_conf_package_imf_e1='1'
+
+    if test -n "$with_imf"; then
+		ac_gdz_imf_incdir=$with_imf/include
+
+        ac_gdz_imf_libdir=$with_imf/lib
+
+        if ! test -d "$ac_gdz_imf_incdir" && ! test -n "$with_imfincludedir"; then
+            echo "ERROR imf include dir does not seem to exist, please check the given base dir \"$with_imf\""
+            exit
+        fi
+        if ! test -d "$ac_gdz_imf_libdir" && ! test -n "$with_imflibdir"; then
+            echo "ERROR imf lib dir does not seem to exist, please check the given base dir \"$with_imf\""
+            exit
+        fi
+    fi
+
+    if test -n "$with_imfincludedir"; then
+		ac_gdz_imf_incdir=$with_imfincludedir
+
+        if ! test -d "$ac_gdz_imf_incdir"; then
+            echo "ERROR imf include dir does not seem to exist, please check the given dir \"$with_imfincludedir\""
+            exit
+        fi
+    fi
+
+    if test -n "$with_imflibdir"; then
+	    ac_gdz_imf_libdir=$with_imflibdir
+
+        if ! test -d "$ac_gdz_imf_libdir"; then
+            echo "ERROR imf lib dir does not seem to exist, please check the given dir \"$with_imflibdir\""
+            exit
+        fi
+    fi
+else
+	ac_gdz_imf_dir=
+	ac_gdz_imf_incdir=
+	ac_gdz_imf_libdir=
 fi
 
 
@@ -1729,6 +1797,7 @@ AC_SUBST(ac_gdz_conf_package_tif_e1)
 AC_SUBST(ac_gdz_conf_package_jpg_e1)
 AC_SUBST(ac_gdz_conf_package_jasper_e1)
 AC_SUBST(ac_gdz_conf_package_png_e1)
+AC_SUBST(ac_gdz_conf_package_imf_e1)
 AC_SUBST(ac_gdz_conf_package_mng_e1)
 AC_SUBST(ac_gdz_conf_package_sepia_e1)
 AC_SUBST(ac_gdz_conf_package_gif_e1)
@@ -1815,6 +1884,8 @@ AC_GDZ_WRITE_COMMON_JPG()
 AC_GDZ_WRITE_COMMON_JASPER()
 
 AC_GDZ_WRITE_COMMON_PNG()
+
+AC_GDZ_WRITE_COMMON_IMF()
 
 AC_GDZ_WRITE_COMMON_MNG()
 
