fixed : VS7 issues (compile probs, possibility to switch to stlport)

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -34,6 +34,8 @@ ac_gdz_conf_package_qt='0'
 ac_gdz_conf_package_qt_e1='0'
 ac_gdz_conf_package_glut='0'
 ac_gdz_conf_package_glut_e1='0'
+ac_gdz_conf_package_stlport='0'
+ac_gdz_conf_package_stlport_e1='0'
 ac_gdz_conf_package_tif='0'
 ac_gdz_conf_package_tif_e1='0'
 ac_gdz_conf_package_jpg='0'
@@ -93,7 +95,7 @@ fi
 
 dnl ############# STL Settings #####################
 
-AC_ARG_WITH(stl,     [  --with-stl=DIR                     Where to find the stl to use],
+AC_ARG_WITH(stl,     [  --with-stl=DIR                     Where to find the stl to use, incompatible with stlport options],
 			,with_stl=no) 
 
 if test "$with_stl" = yes; then
@@ -102,6 +104,73 @@ elif test "$with_stl" = no; then
 	ac_gdz_stl_dir=
 else
 	ac_gdz_stl_dir=$with_stl
+fi
+
+dnl ############# STLPort Settings #####################
+
+AC_ARG_ENABLE(stlport,     [  --enable-stlport                   Build with stlport support, incompatible with --with-stl ],
+			,enable_stlport=no) 
+
+AC_ARG_WITH(stlport,     [  --with-stlport          =DIR       Use DIR/lib DIR/include to find the stlport files, incompatible with --with-stl ],
+			,with_stlport=) 
+
+AC_ARG_WITH(stlportincludedir,     [  --with-stlportincludedir=DIR       Use stlport includes from the given directory, incompatible with --with-stl ],
+			,with_stlportincludedir=) 
+
+AC_ARG_WITH(stlportlibdir,     [  --with-stlportlibdir    =DIR       Use stlport library from the given directory, incompatible with --with-stl ],
+			,with_stlportlibdir=) 
+
+if test "$enable_stlport" = no && test "$with_stlport" = yes; then
+    enable_stlport=yes
+    with_stlport=
+fi
+
+if test "$enable_stlport" = no && test "$with_stlport"X != "X"; then
+    enable_stlport=yes
+fi
+
+if test "$enable_stlport" = yes; then
+	ac_gdz_stlport_incdir=
+	ac_gdz_stlport_libdir=
+	ac_gdz_conf_package_defs=-DOSG_WITH_STLPORT
+	ac_gdz_conf_package_stlport='1'
+	ac_gdz_conf_package_stlport_e1='1'
+
+    if test -n "$with_stlport"; then
+		ac_gdz_stlport_incdir=$with_stlport/stlport
+        ac_gdz_stlport_libdir=$with_stlport/lib
+
+        if ! test -d "$ac_gdz_stlport_incdir" && ! test -n "$with_stlportincludedir"; then
+            echo "ERROR stlport include dir ($ac_gdz_stlport_incdir) does not seem to exist, please check the given base dir \"$with_stlport\""
+            exit
+        fi
+        if ! test -d "$ac_gdz_stlport_libdir" && ! test -n "$with_stlportlibdir"; then
+            echo "ERROR stlport lib dir does not seem to exist, please check the given base dir \"$with_stlport\""
+            exit
+        fi
+    fi
+
+    if test -n "$with_stlportincludedir"; then
+		ac_gdz_stlport_incdir=$with_stlportincludedir
+
+        if ! test -d "$ac_gdz_stlport_incdir"; then
+            echo "ERROR stlport include dir does not seem to exist, please check the given dir \"$with_stlportincludedir\""
+            exit
+        fi
+    fi
+
+    if test -n "$with_stlportlibdir"; then
+	    ac_gdz_stlport_libdir=$with_stlportlibdir
+
+        if ! test -d "$ac_gdz_stlport_libdir"; then
+            echo "ERROR stlport lib dir does not seem to exist, please check the given dir \"$with_stlportlibdir\""
+            exit
+        fi
+    fi
+else
+	ac_gdz_stlport_dir=
+	ac_gdz_stlport_incdir=
+	ac_gdz_stlport_libdir=
 fi
 
 dnl ############# GL Settings #####################
@@ -148,7 +217,7 @@ fi
 if test "$enable_glut" = yes; then
 	ac_gdz_glut_incdir=
 	ac_gdz_glut_libdir=
-	ac_gdz_conf_package_defs=-DOSG_WITH_GLUT
+	ac_gdz_conf_package_defs=$ac_gdz_conf_package_defs' -DOSG_WITH_GLUT'
 	ac_gdz_conf_package_glut='1'
 	ac_gdz_conf_package_glut_e1='1'
 
@@ -477,7 +546,7 @@ fi
 
 dnl ############# MNG Settings #####################
 
-AC_ARG_ENABLE(mng,     [  --enable-mng                   Build with mng supprt],
+AC_ARG_ENABLE(mng,     [  --enable-mng                       Build with mng supprt],
 			,enable_mng=no) 
 AC_ARG_WITH(mng,     [  --with-mng=DIR                     Use DIR/lib DIR/include to find the mng files],
 			,with_mng=) 
@@ -543,7 +612,7 @@ fi
 
 dnl ############# GIF Settings #####################
 
-AC_ARG_WITH(gif,      [  --with-gif                       Build with gif support],
+AC_ARG_WITH(gif,      [  --with-gif                         Build with gif support],
 enable_with_gif=yes, enable_with_gif=no)
 
 AC_ARG_ENABLE(gif,     [  --enable-gif                       Build with gif support],
@@ -1243,6 +1312,7 @@ AC_SUBST(ac_gdz_conf_package_mng_e1)
 AC_SUBST(ac_gdz_conf_package_gif_e1)
 AC_SUBST(ac_gdz_conf_package_gl_e1)
 AC_SUBST(ac_gdz_conf_package_glut_e1)
+AC_SUBST(ac_gdz_conf_package_stlport_e1)
 AC_SUBST(ac_gdz_conf_package_freetype1_e1)
 AC_SUBST(ac_gdz_conf_gvbeta_e1)
 
@@ -1301,6 +1371,7 @@ ac_gdz_common_testmake_in=$ac_gdz_commonconf_dir/Makefile.test.in
 AC_OUTPUT($ac_gdz_common_platform:$ac_gdz_common_platform_in)
 
 AC_GDZ_WRITE_COMMON_STL()
+AC_GDZ_WRITE_COMMON_STLPORT()
 
 AC_GDZ_WRITE_COMMON_GLUT()
 
