added enable-text option.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -56,6 +56,8 @@ ac_gdz_conf_package_sepia='0'
 ac_gdz_conf_package_sepia_e1='0'
 ac_gdz_conf_package_freetype1='0'
 ac_gdz_conf_package_freetype1_e1='0'
+ac_gdz_conf_package_text='0'
+ac_gdz_conf_package_text_e1='0'
 
 ac_gdz_with_add_incdirs=
 ac_gdz_with_add_libdirs=
@@ -834,6 +836,70 @@ else
 	ac_gdz_freetype1_libdir=
 fi
 
+dnl ############# text Settings #####################
+
+AC_ARG_ENABLE(text,     [  --enable-text                        Build with text support],
+			,enable_text=no) 
+AC_ARG_WITH(text,     [  --with-text=DIR                      Use DIR/lib DIR/include to find the freetype2 files],
+			,with_text=) 
+AC_ARG_WITH(textincludedir,     [  --with-textincludedir=DIR            Use freetype2 includes from the given directory],
+			,with_textincludedir=) 
+AC_ARG_WITH(textlibdir,     [  --with-textlibdir=DIR                Use freetype2 lib from the given directory],
+			,with_textlibdir=) 
+
+if test "$enable_text" = no && test "$with_text" = yes; then
+    enable_text=yes
+    with_text=
+fi
+
+if test "$enable_text" = no && test "$with_text"X != "X"; then
+    enable_text=yes
+fi
+
+if test "$enable_text" = yes; then
+	ac_gdz_text_incdir=
+	ac_gdz_text_libdir=
+	ac_gdz_conf_package_text='1'
+	ac_gdz_conf_package_text_e1='1'
+
+    if test -n "$with_text"; then
+		ac_gdz_text_incdir=$with_text/include
+
+        ac_gdz_text_libdir=$with_text/lib
+
+        if ! test -d "$ac_gdz_text_incdir" && ! test -n "$with_textincludedir"; then
+            echo "ERROR text include dir does not seem to exist, please check the given base dir \"$with_text\""
+            exit
+        fi
+        if ! test -d "$ac_gdz_text_libdir" && ! test -n "$with_textlibdir"; then
+            echo "ERROR text lib dir does not seem to exist, please check the given base dir \"$with_text\""
+            exit
+        fi
+    fi
+
+    if test -n "$with_textincludedir"; then
+		ac_gdz_text_incdir=$with_textincludedir
+
+        if ! test -d "$ac_gdz_text_incdir"; then
+            echo "ERROR text include dir does not seem to exist, please check the given dir \"$with_textincludedir\""
+            exit
+        fi
+    fi
+
+    if test -n "$with_textlibdir"; then
+	    ac_gdz_text_libdir=$with_textlibdir
+
+        if ! test -d "$ac_gdz_text_libdir"; then
+            echo "ERROR text lib dir does not seem to exist, please check the given dir \"$with_textlibdir\""
+            exit
+        fi
+    fi
+else
+	ac_gdz_text_dir=
+	ac_gdz_text_incdir=
+	ac_gdz_text_libdir=
+fi
+
 dnl ############# loglevel Settings #####################
 
 AC_ARG_WITH(log_level,     [  --with-log_level=LEVEL              Sets the default log level LEVEL (LOG, FATAL, WARNING, NOTICE, INFO, DEBUG) ],
@@ -1454,6 +1520,7 @@ AC_SUBST(ac_gdz_conf_package_gl_e1)
 AC_SUBST(ac_gdz_conf_package_glut_e1)
 AC_SUBST(ac_gdz_conf_package_stlport_e1)
 AC_SUBST(ac_gdz_conf_package_freetype1_e1)
+AC_SUBST(ac_gdz_conf_package_text_e1)
 AC_SUBST(ac_gdz_conf_gvbeta_e1)
 
 AC_SUBST(ac_gdz_mpatrol_inc_dir_e1)
@@ -1535,6 +1602,8 @@ dnl disabled (files missing)
 dnl AC_GDZ_WRITE_COMMON_MYRINET()
 
 AC_GDZ_WRITE_COMMON_FREETYPE1()
+
+AC_GDZ_WRITE_COMMON_TEXT()
 
 AC_GDZ_WRITE_OSG_CONFIG()
 
