Added support for Visual Studio 2008 to configure-based build system

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3038,6 +3038,58 @@ echo "configure:2839: checking "/ guessing compiler dir for $build-$ac_gdz_compi
             ;;
 
 
+            cl.net2008*|cl9*)
+            
+    
+    ac_gdz_find_prog_dir_result=""
+
+    for drive in c d e f g; do
+     for progdir in "Program Files" "Programme"; do
+      for vsnet in "Microsoft Visual Studio 9.0"; do
+       if test -d "/cygdrive/$drive/$progdir/$vsnet/"; then
+        ac_gdz_find_prog_dir_result="/cygdrive/$drive/$progdir/$vsnet"
+        break 3
+       fi
+      done
+     done
+    done
+
+
+    ac_gdz_compiler_dir=$ac_gdz_find_prog_dir_result/VC
+    ac_gdz_compiler_path=$ac_gdz_compiler_dir/bin
+    ac_gdz_compiler_incl=$ac_gdz_compiler_dir/include
+    ac_gdz_compiler_lib=$ac_gdz_compiler_dir/lib
+    ac_gdz_compiler_exe=cl.exe
+    ac_gdz_linker_exe=link.exe
+    ac_gdz_check_compiler_available=yes
+
+    ac_gdz_compiler_base=cl.net
+
+    if ! test -d "$ac_gdz_compiler_path"; then
+        echo
+        echo "ERROR could not determine compiler dir, tried :"
+
+        for drive in c d e f g; do
+            for progdir in "Program Files" "Programme"; do
+                for vsnet in "Microsoft Visual Studio 9.0"; do
+                    echo "    /cygdrive/$drive/$progdir/$vsnet"
+                done
+            done
+        done
+
+        exit
+    fi
+
+        
+            if test "$enable_stlport" = yes; then
+                ac_gdz_stl_suffix=.stlport
+            else
+                ac_gdz_stl_suffix=.ms_stl
+            fi
+
+            ;;
+
+
             cl.net*)
             
     
