fixed doxygen stuff in dailybuild chanegd make_index to use HTML skeleton file

diff --git a/dist/make_index b/dist/make_index
--- a/dist/make_index
+++ b/dist/make_index
@@ -1,7 +1,8 @@
 #!/bin/sh
 
 # script to create an index page for the dailybuild log directory
-
+# the script expects a index_skeleton.html file to insert itself into,
+# by replacing the ##DAILYBUILD_LOGS## text.
 
 # helper functions
 
@@ -24,6 +25,9 @@ split_name ()
 # main script starts here
 
 logdir=$1
+skeleton=$2
+
+
 
 if test ! -d $logdir -o ! -w $logdir 
 then
@@ -31,30 +35,18 @@ then
     exit 1
 fi
 
-outfile=index.html
-
 cd $logdir
+
+if test ! -r $skeleton 
+then
+    echo "$skeleton not readable, make_index aborted!"
+    exit 1
+fi
+
+outfile=index_raw.html
 
 # HTML header
 cat << EOF > $outfile
-<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd"><html>
-<html>
-<head>
-<title>OpenSG dailybuilds log index</title>
-<style type="text/css">
-<!--
-body	    	{ background-color:#ffffff }
-td.date		{ text-align:left; vertical-align:top }
-td.system	{ text-align:left; vertical-align:top }
-td.status	{ text-align:left; vertical-align:top }
-td.source    	{ text-align:left; vertical-align:top }
-td.snap	    	{ text-align:left; vertical-align:top }
-//-->
-</style>
-</head>
-<body>
-<h1>OpenSG dailybuilds log index</h1>
-<p>
 <table border=1>
 <tr>
 <td><center>Date</center></td><td>System</td>
@@ -104,12 +96,16 @@ do
 
 done
 
-
-
-
 # HTML footer
 cat << EOF >> $outfile
 </table>
-</body>
-</html>
 EOF
+
+# merge with index_skeleton.html
+
+sed -e '/##DAILYBUILD_LOGS##/r index_raw.html' \
+	-e '/##DAILYBUILD_LOGS##/d' < $skeleton > index.html
+
+# remove temporary
+
+rm index_raw.html
